require "../term2"

module Term2
  module Components
    class Cursor
      include Term2::Model

      enum Mode
        Blink
        Static
        Hide
      end

      # InitialBlinkMsg initializes cursor blinking.
      class InitialBlinkMsg < Message; end

      # BlinkMsg signals that the cursor should blink.
      # It contains metadata to tell if the blink message is the one we're expecting.
      class BlinkMsg < Message
        getter tag : Int32

        def initialize(@tag : Int32)
        end
      end

      # BlinkCanceled is sent when a blink operation is canceled/ignored.
      class BlinkCanceled < Message; end

      property blink_speed : Time::Span = 530.milliseconds
      property style : Style = Style.new.reverse(true)
      property text_style : Style = Style.new

      # char is the character under the cursor
      property char : String = " "

      # The ID of this Model as it relates to other cursors (usually 0 unless multiple cursors managed)
      property id : Int32 = 0

      # focus indicates whether the containing input is focused
      property? focus : Bool = false

      # Cursor Blink state (true = visible/hidden depending on logic, effectively "on" cycle)
      # In Go: Blink bool. In Crystal we use this for visibility toggle.
      property blink : Bool = true

      # The ID of the blink message we're expecting to receive.
      @blink_tag : Int32 = 0

      # mode determines the behavior of the cursor
      property mode : Mode = Mode::Blink

      def initialize
      end

      def init : Cmd
        nil
      end

      # Update updates the cursor.
      def update(msg : Msg) : {Cursor, Cmd}
        case msg
        when InitialBlinkMsg
          # We accept all InitialBlinkMsgs generated by the Blink command.
          if @mode != Mode::Blink || !@focus
            return {self, nil}
          end
          return {self, blink_cmd}
        when FocusMsg
          return {self, focus}
        when BlurMsg
          blur
          return {self, nil}
        when BlinkMsg
          # We're choosy about whether to accept blinkMsgs so that our cursor
          # only blinks exactly when it should.

          # Is this model blink-able?
          if @mode != Mode::Blink || !@focus
            return {self, nil}
          end

          # Were we expecting this blink message?
          if msg.tag != @blink_tag
            return {self, nil}
          end

          cmd : Cmd = nil
          if @mode == Mode::Blink
            @blink = !@blink
            cmd = blink_cmd
          end
          return {self, cmd}
        when BlinkCanceled
          # no-op
          return {self, nil}
        end

        {self, nil}
      end

      # SetMode sets the model's cursor mode. This method returns a command.
      def set_mode(mode : Mode) : Cmd
        @mode = mode
        # Reset visibility
        @blink = (@mode == Mode::Hide || !@focus)

        if mode == Mode::Blink
          return Cursor.blink
        end
        nil
      end

      # BlinkCmd is a command used to manage cursor blinking.
      def blink_cmd : Cmd
        if @mode != Mode::Blink
          return
        end

        # Increment tag to invalidate previous blink messages
        @blink_tag += 1

        target_tag = @blink_tag
        delay = @blink_speed

        # Return a command that waits for the delay then emits the message
        Term2::Cmds.tick(delay) do
          BlinkMsg.new(target_tag)
        end
      end

      # Blink is a command used to initialize cursor blinking.
      def self.blink : Cmd
        Term2::Cmds.message(InitialBlinkMsg.new)
      end

      # Focus focuses the cursor to allow it to blink if desired.
      def focus : Cmd
        @focus = true
        # Show the cursor immediately unless explicitly hidden, or start blink cycle visible
        @blink = (@mode == Mode::Hide) ? true : false # Logic matches Go: m.Blink = m.mode == CursorHide

        # Actually, Go logic is: m.Blink = m.mode == CursorHide
        # Wait, if mode is Blink, m.Blink becomes false?
        # Let's trace Go View(): if m.Blink { return TextStyle } else { return Style.Reverse }
        # So m.Blink=true means "Hidden/Text Style", m.Blink=false means "Visible/Block Style"

        # Go: m.Blink = m.mode == CursorHide
        # If mode=Blink, m.Blink = false -> Render Cursor Block (Visible)
        # If mode=Hide, m.Blink = true -> Render Text Style (Hidden)

        @blink = (@mode == Mode::Hide)

        if @mode == Mode::Blink && @focus
          return blink_cmd
        end
        nil
      end

      def focus_cmd : Cmd
        focus
      end

      def blink? : Bool
        @blink
      end

      # Blur blurs the cursor.
      def blur
        @focus = false
        @blink = true # True means "Hidden/Text Style" in Go logic
      end

      # SetChar sets the character under the cursor.
      def set_char(char : String)
        @char = char
      end

      # View displays the cursor.
      def view : View
        # In Go: if m.Blink { return TextStyle } else { return Style...Reverse }
        content = if @blink
          # Cursor Hidden (Blink phase off, or blurred)
          @text_style.inline(true).render(@char)
        else
          # Cursor Visible (Block)
          @style.inline(true).reverse(true).render(@char)
        end
        View.new(content: content)
      end
    end
  end
end
